### ISSUE TITLE
Minio error endpoint : no .Build() method on client factory

### ISSUE THREAD

**Issue by benyaminl** [appany/Minio.AspNetCore#45]
**Describe the bug**
Connection need .Build(), there are no build, cause it error with invalid endpoint

**To Reproduce**
1. Add normal services
2. Try to inject to controller
3. Error, end point error

**Expected behavior**
it should work, as old version (3.1.22)

**Screenshots**
![image](https://user-images.githubusercontent.com/2817332/173020326-2e559df3-ae04-4ead-af90-96ed4b082027.png)
![image](https://user-images.githubusercontent.com/2817332/173022447-8c706df0-13a5-4e57-b80b-8842ec264222.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2, and All OS
 - Browser : Firefox 101, Edge 102
 - Minio version : 4.0 and 4.0.3 (same error, reproducible)

**Additional context**
If I do use manual .Build() on manual Minio, it does works... (bare Minio Client 4.0.3)
See https://github.com/appany/Minio.AspNetCore/blob/main/src/Minio.AspNetCore/MinioClientFactory.cs#L35

**Comment by benyaminl** [comment]
This is wrong, the error because it's has "\"url.minio.com\"", cause the end point error on Depedencies Injection :/

**Comment by sergeyshaykhullin** [comment]
@benyaminl Did you misconfigured minio url?

**Comment by benyaminl** [comment]
> @benyaminl Did you misconfigured minio url?

The ENV on Windows did, 

when I set using .bat file 
eg.
```
set MINIO_ENDPOINT="url.minio.com"
```

using .NET ConfManager GetValues, it produces "\"url.minio.com"\"

so I need to remove it to 
```
set MINIO_ENDPOINT=url.minio.com

I really sorry that it's twice I come here and raise up false alarm issue :/ 
```
