### ISSUE TITLE
Minio.AspNetCore.HealthChecks still on version 4.0.2 on NuGet

### ISSUE THREAD

**Issue by pacoferre** [appany/Minio.AspNetCore#48]
Hello, thanks for this awesome project.

I see in the source code that  Minio.AspNetCore.HealthChecks version is 4.0.5, but it is not published in NuGet

BR,

**Comment by sergeyshaykhullin** [comment]
There was a really long standing issue with CI i don't wanted to touch

Fixed, 4.0.5 in nuget https://www.nuget.org/packages/Minio.AspNetCore.HealthChecks

**Comment by pacoferre** [comment]
Great, thanks a lot :)
