### ISSUE TITLE
Cannot create MinioClient from 4.0.6

### ISSUE THREAD

**Issue by eukuz** [appany/Minio.AspNetCore#57]
@sergeyshaykhullin Thank you for the library!

**Describe the bug**
After updating to minio version 4.0.6, the MinioClient cannot be created with the exception `Minio.Exceptions.ConnectionException: MinIO API responded with message=Connection error:Object reference not set to an instance of an object.`

**To Reproduce**
1. Install nuget packages Minio v4.0.6 and Minio.AspNetCore v4.0.6 
2. Add MinioClient  
`builder.Services.AddMinio(options =>
{
    options.Endpoint = config["Address"];
    options.AccessKey = config["AccessKey"];
    options.SecretKey = config["SecretKey"];
});`
3. Call some method e.g. `BucketExistsAsync`
4. See the error

**Expected behavior**
Minio client is working

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by neoxack** [comment]
Same issue

**Comment by RakouskyS** [comment]
I also have this issue

**Comment by sergeyshaykhullin** [comment]
Should be fixed in https://www.nuget.org/packages/Minio.AspNetCore/4.0.7
