### ISSUE TITLE
.Build() missing

### ISSUE THREAD

**Issue by pacoferre** [appany/Minio.AspNetCore#59]
https://github.com/appany/Minio.AspNetCore/blob/988aac3da9dd92fad0cfc6dd7a10d7c59edf6bdf/src/Minio.AspNetCore/MinioClientFactory.cs#L35

According to Minio Client API, .Build() call method is needed in order to operate.
If not, nothing works, all method calls to Minio clients throws "Object reference not set to an instance of an object" exception.

**Comment by sergeyshaykhullin** [comment]
Fixed in https://www.nuget.org/packages/Minio.AspNetCore/4.0.8
