### ISSUE TITLE
Implementing minio healthchecks issue

### ISSUE THREAD

**Issue by marwa-elfakir-logi** [appany/Minio.AspNetCore#74]
Hello. 
it seems like the latest version of the HealthChecks package doesn't take in consideration that the DI client type changed from MinioClient to IMinioClient 
![image](https://github.com/appany/Minio.AspNetCore/assets/171275881/8b190d75-a988-4582-a93b-1e747a447875)

**Comment by poganytamas** [comment]
Yes, this is an issue needs to be fixed, currently my health check endpoints are not working

**Comment by sergeyshaykhullin** [comment]
https://github.com/appany/Minio.AspNetCore/actions/runs/9651644227
