### ISSUE TITLE
Multiple minio clients support : using name option

### ISSUE THREAD

**Issue by marwa-elfakir-logi** [appany/Minio.AspNetCore#75]
Hello

To add MinioClient, i wanted to use the named extension overload option for multiple clients
![image](https://github.com/appany/Minio.AspNetCore/assets/171275881/fc13a335-1f87-4e2f-9545-5413e8d33cad)

but it seems like it's not an option anymore as of version 6
was it removed ?

**Comment by sergeyshaykhullin** [comment]
@marwa-elfakir-logi 

https://github.com/appany/Minio.AspNetCore/blob/e70f172de73728f582d9932fb2c8e6e819639545/src/Minio.AspNetCore/ServiceCollectionExtensions.cs#L71
